---
packages:
  - vim
  - git
  - bash-completion  
  - openssh-client
  - git
  - net-tools
  - wget
  - lsof
  - unzip
  - openjdk-14-jdk
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common